# Generated by Django 3.0.4 on 2020-03-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=None, max_length=50, unique=True)),
                ('password', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AzurePersonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_group_id', models.CharField(max_length=100)),
                ('person_group_name', models.CharField(max_length=100)),
                ('batch_year', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('Computer', 'Comp'), ('Mechanical', 'Mech'), ('Information Technology', 'IT'), ('Electrical', 'Elect'), ('Electronic and communication', 'EC')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('college_code', models.IntegerField(unique=True)),
                ('gtu_afflicated', models.BooleanField(default=False)),
                ('domain', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('management_college_id', models.IntegerField()),
                ('email', models.EmailField(default=None, max_length=50, unique=True)),
                ('password', models.CharField(default=None, max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.College')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=None, max_length=50, unique=True)),
                ('password', models.CharField(default=None, max_length=50)),
                ('faculty_id', models.IntegerField()),
                ('branch', models.CharField(choices=[('Comp', 'Computer'), ('Mech', 'Mechanical'), ('IT', 'Information Technology'), ('Elect', 'Electrical'), ('EC', 'Electronic and communication')], max_length=30)),
                ('create_hod_id', models.IntegerField(default=None, null=True)),
                ('faculty_type_hod', models.BooleanField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.College')),
                ('create_management_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.CollegeManagement')),
            ],
            options={
                'verbose_name': 'Faculty_model',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=None, max_length=50)),
                ('temperory_id', models.BigIntegerField(null=True)),
                ('enrollment_id', models.BigIntegerField()),
                ('semester_number', models.IntegerField()),
                ('branch', models.CharField(choices=[('Comp', 'Computer'), ('Mech', 'Mechanical'), ('IT', 'Information Technology'), ('Elect', 'Electrical'), ('EC', 'Electronic and communication')], default=None, max_length=50)),
                ('batch_year', models.CharField(default=None, max_length=50)),
                ('sem_start_date', models.DateTimeField()),
                ('sem_end_date', models.DateTimeField()),
                ('student_status', models.CharField(choices=[('detain', 'Detain'), ('active', 'Active'), ('passout', 'Passout'), ('leave', 'Leave')], max_length=20)),
                ('password', models.CharField(default=None, max_length=50)),
                ('email_sent', models.BooleanField(default=False)),
                ('azure_person_id', models.CharField(max_length=50, null=True)),
                ('aws_s3_storage_folder_name', models.CharField(max_length=100, null=True)),
                ('azure_person_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.AzurePersonGroup')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.College')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Faculty')),
            ],
            options={
                'verbose_name': 'Students',
                'verbose_name_plural': 'Studentss',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default=None, max_length=50)),
                ('branch', models.CharField(choices=[('Computer', 'Comp'), ('Mechanical', 'Mech'), ('Information Technology', 'IT'), ('Electrical', 'Elect'), ('Electronic and communication', 'EC')], max_length=30)),
                ('subject_code', models.IntegerField()),
                ('azure_person_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.AzurePersonGroup')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.College')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFaceUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=600)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_subject_lectures', models.IntegerField()),
                ('total_attend', models.IntegerField()),
                ('total_absent', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('week_day', models.CharField(choices=[('Monday', 'mon'), ('Tuesday', 'tues'), ('Wednesday', 'wed'), ('Thursday', 'thur'), ('Friday', 'fri'), ('Saturday', 'sat'), ('Sunday', 'sun')], max_length=10)),
                ('subject_type_theory', models.BooleanField()),
                ('room_number', models.IntegerField(null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Subject')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.AddField(
            model_name='azurepersongroup',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.College'),
        ),
        migrations.CreateModel(
            name='AttendanceTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Faculty')),
                ('periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Periods')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
