# Generated by Django 3.0.4 on 2020-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
