# Generated by Django 3.0.4 on 2020-04-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200331_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='azure_person_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.AzurePersonGroup'),
        ),
    ]
