# Generated by Django 3.0.4 on 2020-03-16 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200316_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=None, max_length=50)),
                ('password', models.CharField(default=None, max_length=50)),
                ('gtu_id', models.IntegerField()),
                ('branch', models.CharField(choices=[('Computer', 'Comp'), ('Mechanical', 'Mech'), ('Information Technology', 'IT'), ('Electrical', 'Elect'), ('Electronic and communication', 'EC')], max_length=30)),
                ('create_hod_id', models.IntegerField(default=None)),
                ('faculty_type_hod', models.BooleanField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.College')),
                ('create_management_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='API.CollegeManagement')),
            ],
            options={
                'verbose_name': 'Faculty_model',
            },
        ),
    ]
