# Generated by Django 3.0.4 on 2020-03-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default=None, max_length=50)),
                ('branch', models.CharField(choices=[('Computer', 'Comp'), ('Mechanical', 'Mech'), ('Information Technology', 'IT'), ('Electrical', 'Elect'), ('Electronic and communication', 'EC')], max_length=30)),
                ('subject_code', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.College')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('week_day', models.CharField(choices=[('Monday', 'mon'), ('Tuesday', 'tues'), ('Wednesday', 'wed'), ('Thursday', 'thur'), ('Friday', 'fri'), ('Saturday', 'sat'), ('Sunday', 'sun')], max_length=10)),
                ('subject_type_theory', models.BooleanField()),
                ('room_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Subject')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
