# Generated by Django 3.0.4 on 2020-03-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_attendancetracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=None, max_length=50)),
                ('temperory_id', models.BigIntegerField()),
                ('enrollment_id', models.BigIntegerField()),
                ('semester_number', models.IntegerField()),
                ('branch', models.CharField(choices=[('Computer', 'Comp'), ('Mechanical', 'Mech'), ('Information Technology', 'IT'), ('Electrical', 'Elect'), ('Electronic and communication', 'EC')], max_length=30)),
                ('batch_year', models.CharField(max_length=50)),
                ('sem_start_date', models.DateTimeField()),
                ('sem_end_date', models.DateTimeField()),
                ('student_status', models.CharField(choices=[('detain', 'Detain'), ('active', 'Active'), ('passout', 'Passout'), ('leave', 'Leave')], max_length=20)),
                ('password', models.CharField(default=None, max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.College')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Faculty')),
            ],
            options={
                'verbose_name': 'Students',
                'verbose_name_plural': 'Studentss',
            },
        ),
        migrations.CreateModel(
            name='StudentFaceUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=600)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_subject_lectures', models.IntegerField()),
                ('total_attend', models.IntegerField()),
                ('total_absent', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='AzureStudentFaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azure_person_group_name', models.CharField(max_length=50)),
                ('azure_person_id', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Student')),
            ],
        ),
    ]
