# Generated by Django 3.0.4 on 2020-04-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200401_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periods',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
