# Generated by Django 3.0.4 on 2020-04-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200402_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.Student'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_numeric_id', models.CharField(auto_created=True, default='ef739295-8d48-4ce7-aae5-7d6d4799c6e4', editable=False, help_text='no need to add', max_length=100, unique=True)),
                ('subject_name', models.CharField(default=None, max_length=50)),
                ('branch', models.CharField(choices=[('Computer', 'Comp'), ('Mechanical', 'Mech'), ('Information Technology', 'IT'), ('Electrical', 'Elect'), ('Electronic and communication', 'EC')], max_length=30)),
                ('subject_code', models.IntegerField()),
                ('azure_person_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.AzurePersonGroup')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.College')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='periods',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.Subject'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.Subject'),
        ),
    ]
