# Generated by Django 3.0.4 on 2020-03-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_azurestudentfaces_student_studentattendance_studentfaceurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='domain',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='gtu_afflicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collegemanagement',
            name='email',
            field=models.EmailField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='create_hod_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='create_management_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.CollegeManagement'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default=None, max_length=50, unique=True),
        ),
    ]
