# Generated by Django 3.0.4 on 2020-03-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200319_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='branch',
            field=models.CharField(choices=[('Comp', 'Computer'), ('Mech', 'Mechanical'), ('IT', 'Information Technology'), ('Elect', 'Electrical'), ('EC', 'Electronic and communication')], max_length=30),
        ),
        migrations.AlterField(
            model_name='periods',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
    ]
